### ISSUE TITLE
capi-workspace doesnt install Bundler 1.17.3

### ISSUE THREAD

**Issue by sethboyles** [cloudfoundry/capi-workspace#26]
capi-workspace needs bundler 1.17.3, but doesnt install it, so running the install script on a new VM fails:

```
Copying "/home/pivotal/.gitconfig" to "/home/pivotal/.gitconfig.bak"
~/workspace/git-hooks-core
./install-scripts/git-hooks.sh: line 26: /home/pivotal/workspace/capi-release/src/cloud_controller_ng/scripts/install-pre-commit.sh: No such file or directory
~/workspace/git-hooks-core ~/workspace/capi-workspace
Already up to date.
~/workspace/capi-workspace
Downloading new cred-alert...done!
Installing latest git-together
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  116k    0  116k    0     0   436k      0 --:--:-- --:--:-- --:--:--  434k
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   691  100   691    0     0   3656      0 --:--:-- --:--:-- --:--:--  3656
100 1076k  100 1076k    0     0  1855k      0 --:--:-- --:--:-- --:--:-- 1855k
git-together
Warning: pivotal/tap/git-author 1.1.0 is already installed and up-to-date
To reinstall 1.1.0, run `brew reinstall git-author`
Traceback (most recent call last):
        2: from /home/pivotal/.rubies/ruby-2.5.5/bin/bundle:23:in `<main>'
        1: from /home/pivotal/.rubies/ruby-2.5.5/lib/ruby/site_ruby/2.5.0/rubygems.rb:296:in `activate_bin_path'
/home/pivotal/.rubies/ruby-2.5.5/lib/ruby/site_ruby/2.5.0/rubygems.rb:277:in `find_spec_for_exe': Could not find 'bundler' (1.17.3) required by your /home/pivotal/workspace/capi-workspace/Gemfile.lock. (Gem::GemNotFoundException)
To update to the latest version installed on your system, run `bundle update --bundler`.
To install the missing version, run `gem install bundler:1.17.3`
```

This can be bypassed by gem installing bundler:

```
 2020-12-01 22:07:30 ⛅️  ruby 2.7.2p137 capi-ws-4 in ~/workspace/capi-workspace
±  |master ✓| → gem install bundler:1.17.3
Fetching bundler-1.17.3.gem
Successfully installed bundler-1.17.3
Parsing documentation for bundler-1.17.3
Installing ri documentation for bundler-1.17.3
Done installing documentation for bundler after 2 seconds
1 gem installed
```

but we should probably add this to a script

**Comment by sethboyles** [comment]
should be fixed with this commit: https://github.com/cloudfoundry/capi-workspace/commit/2c893f707f77e4ee9acd187e6a3a7ad920c4186d
