### ISSUE TITLE
need to manually install libffi7

### ISSUE THREAD

**Issue by sethboyles** [cloudfoundry/capi-workspace#30]
get this error when bundling: 

```
LoadError: libffi.so.7: cannot open shared object file: No such file or directory - /home/pivotal/workspace/capi-release/src/cloud_controller_ng/vendor/cache/ruby/2.7.0/gems/ffi-1.14.2/lib/ffi_c.so
/home/pivotal/workspace/capi-release/src/cloud_controller_ng/vendor/cache/ruby/2.7.0/gems/ffi-1.14.2/lib/ffi.rb:6:in `rescue in <top (required)>'
/home/pivotal/workspace/capi-release/src/cloud_controller_ng/vendor/cache/ruby/2.7.0/gems/ffi-1.14.2/lib/ffi.rb:3:in `<top (required)>'
/home/pivotal/workspace/capi-release/src/cloud_controller_ng/vendor/cache/ruby/2.7.0/gems/ffi-compiler-1.0.1/lib/ffi-compiler/compile_task.rb:4:in `<top (required)>'
/home/pivotal/workspace/capi-release/src/cloud_controller_ng/vendor/cache/ruby/2.7.0/gems/http-parser-1.2.2/ext/Rakefile:1:in `<top (required)>'
```

Because apt doesnt provide libffi7 via apt.  The workaround is to install libffi7 manually.  

## Possible solutions:
* make our workstations based off of Ubuntu 20 instead of 18
* use dockerfile (prob hard)
* install libffi7 on capi-workspace script

**Comment by sethboyles** [comment]
https://askubuntu.com/questions/1286772/libffi-so-7-cannot-open-shared-object-file-no-such-file-or-directory
